### PR TITLE
PHP: unlocking patch version

### PR DESCRIPTION
**Pull request by bryanlatten**

### CODE REVIEW

**Comment by chrishenry** [comment]
Whheeee!

**Comment by ko-be** [comment]
can we do >= a certain version?  or if we have a way to test which version actually gets built out, that'd work too.

**Comment by bryanlatten** [comment]
@ko-be does that work? I thought it's not supported as part of `apt-get`

that said, the PPA we're using only stocks one patch version at a time

**Comment by ko-be** [comment]
@bryanlatten you're right, only = is supported.

We should have some kind of tests for proper php version though.

**Comment by bryanlatten** [comment]
waiting on @bossjones to help me with that travis testing!

**Pull request merged**
