### PR TITLE
Dockerfile: updated to parent’s 7.0

### PR DESCRIPTION
**Pull request by bryanlatten**
- Using parent's 7.0 branch: https://github.com/behance/docker-nginx/releases/tag/7.0.0, which switches to `nginx-light` instead of `nginx-full`

### CODE REVIEW

**Comment by ko-be** [comment]
👍

**Comment by bossjones** [comment]
what are the differences with nginx-full and nginx-light ?

**Comment by bossjones** [comment]
Talked via slack. Main list of differences I saw came from 2 sources:

1. https://wiki.debian.org/Nginx
2. http://askubuntu.com/questions/553937/what-is-the-difference-between-the-core-full-extras-and-light-packages-for-ngi

Went through as many as possible to confirm we don't break anything. Only thing I see currently is uwsgi breaks, which will break activity feed for flotilla and eventually ethos activity unless we remove `light` and install `full` inside of the activity Dockerfile. FYI

other than that, LGTM as far as I can tell.

**Comment by bossjones** [comment]
👍

**Pull request merged**
