### PR TITLE
add secure http headers

### PR DESCRIPTION
**Pull request by ko-be**
Adding some secure http headers, as recommended by https://securityheaders.io/

### CODE REVIEW

**Comment by remotelyliving** [comment]
👍

**Comment by bryanlatten** [comment]
@ko-be can you promote this instead to github.com/behance/docker-nginx?

**Comment by ko-be** [comment]
@bryanlatten I put it here in docker-php, as this file container/root/etc/nginx/sites-available/default in this repo appears to override the version in docker-nginx.  Should I just put it in both places?

**Comment by bryanlatten** [comment]
We'll need the

**Comment by ko-be** [comment]
Tests for this container will now fail until we merge https://github.com/behance/docker-nginx/pull/44 & update all Dockerfiles to use the new docker-nginx container.

**Comment by bossjones** [comment]
👍

**Comment by bryanlatten** [comment]
👍

**Pull request merged**
